"""Initial schema baseline from current ORM models.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-22
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_prompts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prompt_date", sa.Date(), nullable=False),
        sa.Column("word_1", sa.Text(), nullable=False),
        sa.Column("word_2", sa.Text(), nullable=False),
        sa.Column("word_3", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "withdrawn", name="prompt_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_prompts")),
        sa.UniqueConstraint("prompt_date", name="uq_daily_prompts_prompt_date"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("descope_subject", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("username_normalized", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_upload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "incomplete",
                "active",
                "suspended",
                "pending_deletion",
                "deleted",
                name="user_status",
            ),
            nullable=False,
        ),
        sa.Column("profile_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("descope_subject", name=op.f("uq_users_descope_subject")),
        sa.UniqueConstraint("username_normalized", name=op.f("uq_users_username_normalized")),
    )
    op.create_index("ix_users_avatar_upload_id", "users", ["avatar_upload_id"], unique=False)
    op.create_table(
        "creative_publications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "creative_type", sa.Enum("sketch", "story", name="creative_type"), nullable=False
        ),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("visibility", sa.Enum("public", name="submission_visibility"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "processing", "published", "hidden", "removed", "deleted", name="submission_status"
            ),
            nullable=False,
        ),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("reflection_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["daily_prompts.id"],
            name=op.f("fk_creative_publications_prompt_id_daily_prompts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_creative_publications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creative_publications")),
    )
    op.create_index(
        "ix_creative_publications_creative_type",
        "creative_publications",
        ["creative_type"],
        unique=False,
    )
    op.create_index(
        "ix_creative_publications_prompt_id_published_at_id",
        "creative_publications",
        ["prompt_id", sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_creative_publications_published_active",
        "creative_publications",
        [sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_creative_publications_published_at_id",
        "creative_publications",
        [sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_creative_publications_user_id_published_at",
        "creative_publications",
        ["user_id", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_creative_publications_user_id_published_at_id",
        "creative_publications",
        ["user_id", sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_table(
        "creative_type_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "creative_type", sa.Enum("sketch", "story", name="creative_type"), nullable=False
        ),
        sa.Column("remember_timer_option", sa.Boolean(), nullable=False),
        sa.Column(
            "remembered_timer_mode",
            sa.Enum("countdown", "no_timer", name="timer_mode"),
            nullable=True,
        ),
        sa.Column("remembered_timer_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_creative_type_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "creative_type", name=op.f("pk_creative_type_preferences")
        ),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_idempotency_keys_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint(
            "user_id", "endpoint", "key", name="uq_idempotency_keys_user_endpoint_key"
        ),
    )
    op.create_index(
        "ix_idempotency_keys_expires_at", "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("submission", "reflection", "profile", name="report_target_type"),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "inappropriate",
                "harassment",
                "hate",
                "spam",
                "intellectual_property",
                "self_harm",
                "other",
                name="report_reason",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "reviewing", "resolved", "dismissed", name="report_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_reports_reviewed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "ix_reports_reporter_target_open",
        "reports",
        ["reporter_user_id", "target_type", "target_id"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_index(
        "ix_reports_status_created_at", "reports", ["status", "created_at"], unique=False
    )
    op.create_table(
        "sketch_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "timer_mode", sa.Enum("countdown", "no_timer", name="timer_mode"), nullable=False
        ),
        sa.Column("selected_timer_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "ready_for_photo",
                "uploading",
                "completed",
                "abandoned",
                "expired",
                name="sketch_session_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paused_total_seconds", sa.Integer(), nullable=False),
        sa.Column("timer_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finish_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("photo_step_reached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upload_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upload_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["daily_prompts.id"],
            name=op.f("fk_sketch_sessions_prompt_id_daily_prompts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sketch_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sketch_sessions")),
    )
    op.create_index(
        "ix_sketch_sessions_prompt_id_created_at",
        "sketch_sessions",
        ["prompt_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_sketch_sessions_user_id_created_at",
        "sketch_sessions",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "story_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "timer_mode", sa.Enum("countdown", "no_timer", name="timer_mode"), nullable=False
        ),
        sa.Column("selected_timer_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "writing",
                "completed",
                "abandoned",
                "expired",
                name="story_session_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paused_total_seconds", sa.Integer(), nullable=False),
        sa.Column("timer_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finish_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("abandoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["daily_prompts.id"],
            name=op.f("fk_story_sessions_prompt_id_daily_prompts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_story_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_sessions")),
    )
    op.create_index(
        "ix_story_sessions_prompt_id_created_at",
        "story_sessions",
        ["prompt_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_story_sessions_user_id_created_at",
        "story_sessions",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose", sa.Enum("submission", "avatar", name="upload_purpose"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "uploaded",
                "verified",
                "processing",
                "ready",
                "consumed",
                "failed",
                "expired",
                "deleted",
                name="upload_status",
            ),
            nullable=False,
        ),
        sa.Column("storage_bucket", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.Text(), nullable=True),
        sa.Column(
            "derivative_status",
            sa.Enum("pending", "ready", "failed", name="derivative_status"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_uploads_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_uploads_storage_key")),
    )
    op.create_index(
        "ix_uploads_status_expires_at", "uploads", ["status", "expires_at"], unique=False
    )
    op.create_index(
        "ix_uploads_user_id_created_at",
        "uploads",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # Deferred: users.avatar_upload_id → uploads.id (circular dependency).
    op.create_foreign_key(
        "fk_users_avatar_upload_id",
        "users",
        "uploads",
        ["avatar_upload_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "user_blocks",
        sa.Column("blocker_user_id", sa.Uuid(), nullable=False),
        sa.Column("blocked_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "blocker_user_id <> blocked_user_id",
            name=op.f("ck_user_blocks_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["blocked_user_id"],
            ["users.id"],
            name=op.f("fk_user_blocks_blocked_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["blocker_user_id"],
            ["users.id"],
            name=op.f("fk_user_blocks_blocker_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("blocker_user_id", "blocked_user_id", name=op.f("pk_user_blocks")),
    )
    op.create_index(
        "ix_user_blocks_blocked_user_id", "user_blocks", ["blocked_user_id"], unique=False
    )
    op.create_index(
        "ix_user_blocks_blocker_user_id", "user_blocks", ["blocker_user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("notification_time_local", sa.Time(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column(
            "appearance", sa.Enum("system", "light", "dark", name="appearance"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "moderation_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operator_identity", sa.Text(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "hide_submission",
                "remove_submission",
                "restore_submission",
                "hide_reflection",
                "remove_reflection",
                "restore_reflection",
                "suspend_user",
                "restore_user",
                "resolve_report",
                "dismiss_report",
                name="moderation_action_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "target_type",
            sa.Enum("submission", "reflection", "profile", name="report_target_type"),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_moderation_actions_report_id_reports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moderation_actions")),
    )
    op.create_index(
        "ix_moderation_actions_created_at",
        "moderation_actions",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "publication_likes",
        sa.Column("publication_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["creative_publications.id"],
            name=op.f("fk_publication_likes_publication_id_creative_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_publication_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("publication_id", "user_id", name=op.f("pk_publication_likes")),
    )
    op.create_index(
        "ix_publication_likes_user_id_created_at",
        "publication_likes",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "reflections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("published", "hidden", "removed", "deleted", name="reflection_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["creative_publications.id"],
            name=op.f("fk_reflections_submission_id_creative_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reflections_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reflections")),
    )
    op.create_index(
        "ix_reflections_active",
        "reflections",
        ["submission_id", sa.literal_column("created_at ASC"), sa.literal_column("id ASC")],
        unique=False,
        postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_reflections_submission_id_created_at_id",
        "reflections",
        ["submission_id", sa.literal_column("created_at ASC"), sa.literal_column("id ASC")],
        unique=False,
    )
    op.create_index(
        "ix_reflections_user_id_created_at",
        "reflections",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "sketch_session_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sketch_session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "started",
                "paused",
                "resumed",
                "timer_completed",
                "finished_early",
                "photo_step_reached",
                "upload_started",
                "upload_completed",
                "submission_created",
                "abandoned",
                name="sketch_session_event_type",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sketch_session_id"],
            ["sketch_sessions.id"],
            name=op.f("fk_sketch_session_events_sketch_session_id_sketch_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sketch_session_events")),
    )
    op.create_index(
        "ix_sketch_session_events_sketch_session_id",
        "sketch_session_events",
        ["sketch_session_id"],
        unique=False,
    )
    op.create_table(
        "sketch_submissions",
        sa.Column("publication_id", sa.Uuid(), nullable=False),
        sa.Column("sketch_session_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["creative_publications.id"],
            name=op.f("fk_sketch_submissions_publication_id_creative_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sketch_session_id"],
            ["sketch_sessions.id"],
            name=op.f("fk_sketch_submissions_sketch_session_id_sketch_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_sketch_submissions_upload_id_uploads"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("publication_id", name=op.f("pk_sketch_submissions")),
        sa.UniqueConstraint(
            "sketch_session_id", name=op.f("uq_sketch_submissions_sketch_session_id")
        ),
        sa.UniqueConstraint("upload_id", name=op.f("uq_sketch_submissions_upload_id")),
    )
    op.create_table(
        "story_session_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("story_session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "started",
                "paused",
                "resumed",
                "timer_completed",
                "finished_early",
                "writing_started",
                "draft_saved",
                "submission_created",
                "abandoned",
                name="story_session_event_type",
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("client_occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["story_session_id"],
            ["story_sessions.id"],
            name=op.f("fk_story_session_events_story_session_id_story_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_session_events")),
    )
    op.create_index(
        "ix_story_session_events_story_session_id",
        "story_session_events",
        ["story_session_id"],
        unique=False,
    )
    op.create_table(
        "story_submissions",
        sa.Column("publication_id", sa.Uuid(), nullable=False),
        sa.Column("story_session_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["creative_publications.id"],
            name=op.f("fk_story_submissions_publication_id_creative_publications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_session_id"],
            ["story_sessions.id"],
            name=op.f("fk_story_submissions_story_session_id_story_sessions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("publication_id", name=op.f("pk_story_submissions")),
        sa.UniqueConstraint("story_session_id", name=op.f("uq_story_submissions_story_session_id")),
    )
    op.create_table(
        "activity_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum("submission_liked", "reflection_added", name="activity_event_type"),
            nullable=False,
        ),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("reflection_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_activity_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_activity_events_recipient_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reflection_id"],
            ["reflections.id"],
            name=op.f("fk_activity_events_reflection_id_reflections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["creative_publications.id"],
            name=op.f("fk_activity_events_submission_id_creative_publications"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    op.create_index(
        "ix_activity_events_recipient_user_id_created_at",
        "activity_events",
        ["recipient_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_events_recipient_user_id_created_at", table_name="activity_events")
    op.drop_table("activity_events")
    op.drop_table("story_submissions")
    op.drop_index("ix_story_session_events_story_session_id", table_name="story_session_events")
    op.drop_table("story_session_events")
    op.drop_table("sketch_submissions")
    op.drop_index("ix_sketch_session_events_sketch_session_id", table_name="sketch_session_events")
    op.drop_table("sketch_session_events")
    op.drop_index("ix_reflections_user_id_created_at", table_name="reflections")
    op.drop_index("ix_reflections_submission_id_created_at_id", table_name="reflections")
    op.drop_index(
        "ix_reflections_active",
        table_name="reflections",
        postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"),
    )
    op.drop_table("reflections")
    op.drop_index("ix_publication_likes_user_id_created_at", table_name="publication_likes")
    op.drop_table("publication_likes")
    op.drop_index("ix_moderation_actions_created_at", table_name="moderation_actions")
    op.drop_table("moderation_actions")
    op.drop_table("user_preferences")
    op.drop_index("ix_user_blocks_blocker_user_id", table_name="user_blocks")
    op.drop_index("ix_user_blocks_blocked_user_id", table_name="user_blocks")
    op.drop_table("user_blocks")
    op.drop_index("ix_uploads_user_id_created_at", table_name="uploads")
    op.drop_index("ix_uploads_status_expires_at", table_name="uploads")
    op.drop_constraint("fk_users_avatar_upload_id", "users", type_="foreignkey")
    op.drop_table("uploads")
    op.drop_index("ix_story_sessions_user_id_created_at", table_name="story_sessions")
    op.drop_index("ix_story_sessions_prompt_id_created_at", table_name="story_sessions")
    op.drop_table("story_sessions")
    op.drop_index("ix_sketch_sessions_user_id_created_at", table_name="sketch_sessions")
    op.drop_index("ix_sketch_sessions_prompt_id_created_at", table_name="sketch_sessions")
    op.drop_table("sketch_sessions")
    op.drop_index("ix_reports_status_created_at", table_name="reports")
    op.drop_index(
        "ix_reports_reporter_target_open",
        table_name="reports",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_table("reports")
    op.drop_index("ix_idempotency_keys_expires_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("creative_type_preferences")
    op.drop_index(
        "ix_creative_publications_user_id_published_at_id", table_name="creative_publications"
    )
    op.drop_index(
        "ix_creative_publications_user_id_published_at", table_name="creative_publications"
    )
    op.drop_index("ix_creative_publications_published_at_id", table_name="creative_publications")
    op.drop_index(
        "ix_creative_publications_published_active",
        table_name="creative_publications",
        postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_creative_publications_prompt_id_published_at_id", table_name="creative_publications"
    )
    op.drop_index("ix_creative_publications_creative_type", table_name="creative_publications")
    op.drop_table("creative_publications")
    op.drop_index("ix_users_avatar_upload_id", table_name="users")
    op.drop_table("users")
    op.drop_table("daily_prompts")
    # ### end Alembic commands ###
